language: php
php:
- "7.2"
- "7.3"
cache: npm
env:
- TRAVIS_NODE_VERSION="11"

services:
- docker
- mysql
addons:
  mariadb: '10.3'
  chrome: stable # Used by Dusk

before_script:
- set -e
- cp .env.travis .env
- cp .env.travis.testing .env.testing
- nvm install $TRAVIS_NODE_VERSION
- mysql -e 'create database monicag' # Used by Dusk
- mysql -e 'create database monicag_testing' # Used by PHPUnit
- mysql -e "create user 'monika'@'localhost' IDENTIFIED BY 'justmonika';"
- mysql -e "grant all on monicag.* to 'monika'@'localhost';"
- mysql -e "grant all on monicag_testing.* to 'monika'@'localhost';"
- travis_retry composer install --no-interaction --prefer-dist --no-suggest
- php artisan key:generate
- php artisan key:generate --env=testing
- php artisan migrate --seed &
  php artisan migrate --seed --env=testing &
- npm ci
- npm run production
- php artisan serve >& /dev/null &

script:
- set -e
- composer phpunit
- composer dusk
