language: php
php:
- "7.2"
- "7.3"
cache: npm
env:
- TRAVIS_NODE_VERSION="11"

services:
- docker
- mysql
addons:
  mariadb: '10.3'
  chrome: stable # Used by Dusk

before_script:
- set -e
- cp .env.travis .env # Composer reads APP_ENV, it assumes production by default which would prevent Dusk installation
- travis_retry composer install --no-interaction --prefer-dist --no-suggest
- cp .env.travis .env.testing
- cp .env.travis .env.dusk.local
- nvm install $TRAVIS_NODE_VERSION
- mysql -e 'create database monicag' # Used by PHPUnit
- mysql -e "create user 'monika'@'localhost' IDENTIFIED BY 'justmonika';"
- mysql -e "grant all on monicag.* to 'monika'@'localhost';"
- php artisan key:generate
- php artisan key:generate --env=testing
- php artisan key:generate --env=dusk.local
- php artisan migrate --seed &
  php artisan migrate --seed --env=testing &
- php artisan passport:install
- php artisan dusk:chrome-driver
- npm ci
- npm run production
- php artisan serve --env=dusk.local >& /dev/null &

script:
- set -e
- composer phpunit
- composer dusk
