version: "3"

services:
  web:
    # image: monicag:latest # For production
    build:
      context: .
    depends_on:
      - mariadb
    container_name: app
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: MoniCAG
      DB_USERNAME: Monika
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html # Not to do in production
    networks:
      - local
  mariadb:
    image: mariadb
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: MoniCAG
      MYSQL_USER: Monika
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - local

networks:
  local:
